name: Deploy to 000webhost

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install FTP Client
      run: sudo apt-get install -y lftp

    - name: Deploy to 000webhost
      run: |
        lftp -e "set ftp:ssl-allow no; open -u saerefontedesite -p SLt!eM@D5&jb8kZE ftp.000webhost.com; mirror -R -e . /public_html; bye"
